#---------------------------------------------------------------------------------------------------
# %L                                                                                               -
# protocol-model                                                                          -
# %%                                                                                               -
# Copyright (C) 2016 - 2018 République et Canton de Genève                                         -
# %%                                                                                               -
# This program is free software: you can redistribute it and/or modify                             -
# it under the terms of the GNU Affero General Public License as published by                      -
# the Free Software Foundation, either version 3 of the License, or                                -
# (at your option) any later version.                                                              -
#                                                                                                  -
# This program is distributed in the hope that it will be useful,                                  -
# but WITHOUT ANY WARRANTY; without even the implied warranty of                                   -
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                                     -
# GNU General Public License for more details.                                                     -
#                                                                                                  -
# You should have received a copy of the GNU Affero General Public License                         -
# along with this program. If not, see <http://www.gnu.org/licenses/>.                             -
# L%                                                                                               -
#---------------------------------------------------------------------------------------------------

image: $IMAGE_DOCKER_MVN_JDK8

variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_REPO_OPTS: "-Dmaven.repo.local=.m2/repository -s $MVN_SETTINGS -Dorg.slf4j.simpleLogger.showDateTime=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  #Sonar pre-build
  SONAR_PRE_BUILD_CMD: "org.jacoco:jacoco-maven-plugin:prepare-agent"
  #Sonar post-build
  SONAR_POST_BUILD_CMD: "$SONAR_MAVEN_PLUGIN -Dsonar.host.url=$SONAR2_URL -Dsonar.login=$SONAR2_TOKEN"

stages:
- build
- test

maven-build:
  stage: build
  script:
  - mvn $MAVEN_REPO_OPTS $MAVEN_CLI_OPTS clean package
  cache:
    key: chvote-protocol-model-$CI_COMMIT_REF_NAME
    paths:
    - .m2/repository/

# Build, test and run Sonar analysis for dev branches (all except master and support branches)
sonar-preview:
  stage: test
  script:
  - mvn $MAVEN_REPO_OPTS $MAVEN_CLI_OPTS clean $SONAR_PRE_BUILD_CMD verify $SONAR_POST_BUILD_CMD -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.url=$GITLAB_URL
  cache:
    key: chvote-protocol-model-$CI_COMMIT_REF_NAME
    paths:
    - .m2/repository/
  except:
  - master
  - /^support-\d+\.\d+\.\d+$/

# Full build and artifact deployment for publishing branches ("master" and "support-x.y.z")
sonar-deploy:
  stage: test
  script:
  - mvn $MAVEN_REPO_OPTS $MAVEN_CLI_OPTS clean $SONAR_PRE_BUILD_CMD deploy $SONAR_POST_BUILD_CMD
  cache:
    key: chvote-protocol-model-$CI_COMMIT_REF_NAME
    paths:
    - .m2/repository/
  only:
  - master
  - /^support-\d+\.\d+\.\d+$/
